stages:
  - build
  - test
  - deploy

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

#before_script:
#  - cd reddit
#  - bundle install

.build_job:
  stage: build
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  image: ruby:2.4.2
#  services:
#    - mongo:latest
  script:
    - cd reddit
    - bundle install
    - ruby simpletest.rb

.test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

.deploy_job:
  stage: deploy
  script:
    - echo 'Deploy'
