---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host | default .Release.Name }}
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  number: 80
            path: /
