---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-deployment
  labels:
    app: comment
    component: comment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: comment
  template:
    metadata:
      name: comment
      labels:
        app: reddit
        component: comment
    spec:
      containers:
      - name: comment
        image: voitenkov/comment
        resources:
          limits:
            memory: 256Mi
            cpu: "1"
        env:
        - name: COMMENT_DATABASE_HOST
          value: mongo
