---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  labels:
    app: post
    component: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: post
  template:
    metadata:
      name: post
      labels:
        app: reddit
        component: post
    spec:
      containers:
      - name: post
        image: voitenkov/post
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        env:
        - name: POST_DATABASE_HOST
          value: mongo
